query  {
    git(url: "github.com/dagger/dagger") {
        branch(name: "main") {
            tree {
                directory(path: "sdk/nodejs") {
                    id
                }
            }
        }
    }
}