query install ($dirID: DirectoryID!) {
    node {
        withVersion(version: "20-alpine3.17") {
            withYarn {
                withSource(source: $dirID) {
                    build {
                        container {
                            directory(path: "dist") {
                                entries
                            }
                        }
                    }
                }
            }
        }
    }

}